Algoritmo "ContadorProcedimento"
Var
   In, Fi, Inc: inteiro
Procedimento Contador(I, F, Incr: inteiro )
var
   C: inteiro
inicio
      Para C <- I ate F passo Incr faca
         Escreva("",C,"")
      fimpara
fimprocedimento
Inicio
      Escreva("Inicio: ")
      Leia(In)
      Escreva("Fim: ")
      Leia(Fi)
      Escreva("Incremento: ")
      Leia(Inc)
      Contador(In, Fi, Inc)


Fimalgoritmo